### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rehat101** [rehat101/ag-grid#1]
### A list of things to do

- [x] save 
- [x] remove
- [ ] retrieve 
- [x] arrow key to navigate through different cells 
- [ ] ALT+D short cut for selected data delete 
- [ ] ALT+S Short cut for saving the record 
- [ ] date field
- [x] Text field
- [x] dropdown
- [ ] numeric field
- [ ] decimal field with 2/3 decimal points
- [x] one button per each row.
- [x] different color while editing a row
